export type Era = "고대" | "중세" | "근대" | "근현대" | "현대";

export type HistoryEvent = {
  id: string;
  country: string;
  date: string;
  year: number;
  title: string;
  era: Era;
  description: string;
  category?: "history" | "holiday";
  url?: string; // 상세 링크 추가
};

export const historyEvents: HistoryEvent[] = [
  // --- 공휴일 ---
  {
    id: "global-0101",
    country: "세계",
    date: "01-01",
    year: 2024,
    title: "새해",
    era: "현대",
    description: "새해 첫날을 기념하는 전 세계 공통 공휴일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/새해",
  },
  {
    id: "kr-0505",
    country: "한국",
    date: "05-05",
    year: 2024,
    title: "어린이날",
    era: "현대",
    description: "어린이의 인격을 소중히 여기고 행복을 도모하는 날.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/어린이날_(대한민국)",
  },
  {
    id: "kr-0606",
    country: "한국",
    date: "06-06",
    year: 2024,
    title: "현충일",
    era: "현대",
    description: "나라를 위해 목숨을 바친 순국선열과 호국영령을 추모하는 날.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/현충일",
  },
  {
    id: "kr-1003",
    country: "한국",
    date: "10-03",
    year: 2333,
    title: "개천절",
    era: "고대",
    description: "우리 민족 최초 국가인 고조선 건국을 기념하는 날.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/개천절",
  },
  {
    id: "kr-1225",
    country: "세계",
    date: "12-25",
    year: 2024,
    title: "크리스마스",
    era: "현대",
    description: "예수 그리스도의 탄생을 기념하는 날.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/크리스마스",
  },
  {
    id: "us-1111",
    country: "미국",
    date: "11-11",
    year: 2024,
    title: "재향군인의 날",
    era: "현대",
    description: "참전 용사들을 기리는 미국의 공휴일 (Veterans Day).",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/재향군인의_날",
  },
  {
    id: "jp-0211",
    country: "일본",
    date: "02-11",
    year: 2024,
    title: "건국기념일",
    era: "현대",
    description: "일본의 건국을 기념하는 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/건국기념일_(일본)",
  },
  {
    id: "jp-0429",
    country: "일본",
    date: "04-29",
    year: 2024,
    title: "쇼와 날",
    era: "현대",
    description: "쇼와 천황의 생일을 기념하는 공휴일 (골든위크 시작).",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/쇼와의_날",
  },
  {
    id: "jp-0503",
    country: "일본",
    date: "05-03",
    year: 2024,
    title: "헌법기념일",
    era: "현대",
    description: "일본국 헌법 시행을 기념하는 날.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/헌법기념일_(일본)",
  },
  {
    id: "jp-0504",
    country: "일본",
    date: "05-04",
    year: 2024,
    title: "녹색의 날",
    era: "현대",
    description: "자연과 친해지며 그 은혜에 감사하는 날.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/녹색의_날",
  },
  {
    id: "jp-1103",
    country: "일본",
    date: "11-03",
    year: 2024,
    title: "문화의 날",
    era: "현대",
    description: "자유와 평화를 사랑하고 문화를 추진하는 날.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/문화의_날",
  },
  {
    id: "jp-1123",
    country: "일본",
    date: "11-23",
    year: 2024,
    title: "근로감사의 날",
    era: "현대",
    description: "근로를 존중하고 생산을 축하하며 국민이 서로 감사하는 날.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/근로감사의_날",
  },
  {
    id: "cn-1001-holiday",
    country: "중국",
    date: "10-01",
    year: 2024,
    title: "국경절 (공휴일)",
    era: "현대",
    description: "중화인민공화국 건국을 기념하는 중국 최대의 공휴일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/국경절_(중국)",
  },
  // --- 한국사 (근현대/현대) ---
  {
    id: "kr-0301-1919",
    country: "한국",
    date: "03-01",
    year: 1919,
    title: "3·1 운동",
    era: "근현대",
    description: "일제강점기에 일어난 거족적인 독립 만세 운동.",
    url: "https://ko.wikipedia.org/wiki/3·1_운동",
  },
  {
    id: "kr-0815-1945",
    country: "한국",
    date: "08-15",
    year: 1945,
    title: "광복절",
    era: "근현대",
    description: "일제강점기에서 벗어나 독립을 맞이한 날.",
    url: "https://ko.wikipedia.org/wiki/광복절",
  },
  {
    id: "kr-0625-1950",
    country: "한국",
    date: "06-25",
    year: 1950,
    title: "6·25 전쟁 발발",
    era: "근현대",
    description: "북한군의 남침으로 시작된 한국전쟁.",
    url: "https://ko.wikipedia.org/wiki/6.25_전쟁",
  },
  {
    id: "kr-0419-1960",
    country: "한국",
    date: "04-19",
    year: 1960,
    title: "4·19 혁명",
    era: "현대",
    description: "이승만 독재 정권에 항거한 민주주의 시민 혁명.",
    url: "https://ko.wikipedia.org/wiki/4·19_혁명",
  },
  {
    id: "kr-0518-1980",
    country: "한국",
    date: "05-18",
    year: 1980,
    title: "5·18 민주화운동",
    era: "현대",
    description: "광주 시민들이 신군부 독재에 항거한 민주화 운동.",
    url: "https://ko.wikipedia.org/wiki/5·18_광주_민주화_운동",
  },
  {
    id: "kr-0629-1987",
    country: "한국",
    date: "06-29",
    year: 1987,
    title: "6·29 선언",
    era: "현대",
    description: "대통령 직선제 개헌을 이끌어낸 민주화 선언.",
    url: "https://ko.wikipedia.org/wiki/6·29_선언",
  },
  {
    id: "kr-1009-1446",
    country: "한국",
    date: "10-09",
    year: 1446,
    title: "훈민정음 반포",
    era: "근대",
    description: "세종대왕이 훈민정음을 반포한 날.",
    url: "https://ko.wikipedia.org/wiki/훈민정음",
  },
  // --- 세계사 (근현대/현대) ---
  {
    id: "fr-0714-1789",
    country: "프랑스",
    date: "07-14",
    year: 1789,
    title: "바스티유 감옥 습격",
    era: "근대",
    description: "프랑스 혁명의 도화선이 된 사건.",
    url: "https://ko.wikipedia.org/wiki/바스티유_감옥_습격",
  },
  {
    id: "us-0704-1776",
    country: "미국",
    date: "07-04",
    year: 1776,
    title: "미국 독립기념일",
    era: "근대",
    description: "미합중국 독립선언서가 채택된 날.",
    url: "https://ko.wikipedia.org/wiki/미국_독립기념일",
  },
  {
    id: "us-0911-2001",
    country: "미국",
    date: "09-11",
    year: 2001,
    title: "9·11 테러",
    era: "현대",
    description: "알카에다에 의한 미국 동시다발 테러 사건.",
    url: "https://ko.wikipedia.org/wiki/9·11_테러",
  },
  {
    id: "de-1109-1989",
    country: "독일",
    date: "11-09",
    year: 1989,
    title: "베를린 장벽 붕괴",
    era: "현대",
    description: "냉전 종식과 독일 통일의 상징적 사건.",
    url: "https://ko.wikipedia.org/wiki/베를린_장벽",
  },
  {
    id: "de-1003-1990",
    country: "독일",
    date: "10-03",
    year: 1990,
    title: "독일 통일",
    era: "현대",
    description: "서독과 동독이 공식적으로 재통일된 날.",
    url: "https://ko.wikipedia.org/wiki/독일의_재통일",
  },
  {
    id: "jp-0806-1945",
    country: "일본",
    date: "08-06",
    year: 1945,
    title: "히로시마 원폭 투하",
    era: "근현대",
    description: "인류 역사상 최초로 전쟁 중 핵무기가 사용됨.",
    url: "https://ko.wikipedia.org/wiki/히로시마·나가사키_원자폭탄_투하",
  },
  {
    id: "jp-0815-1945",
    country: "일본",
    date: "08-15",
    year: 1945,
    title: "무조건 항복 선언",
    era: "근현대",
    description: "쇼와 일왕의 항복 선언으로 제2차 세계대전 종전.",
    url: "https://ko.wikipedia.org/wiki/일본의_항복",
  },
  {
    id: "cn-1001-1949",
    country: "중국",
    date: "10-01",
    year: 1949,
    title: "중화인민공화국 수립",
    era: "근현대",
    description: "마오쩌둥이 천안문 광장에서 건국을 선포함.",
    url: "https://ko.wikipedia.org/wiki/중화인민공화국",
  },
  {
    id: "ru-1107-1917",
    country: "러시아",
    date: "11-07",
    year: 1917,
    title: "10월 혁명",
    era: "근대",
    description: "볼셰비키가 주도한 러시아 사회주의 혁명 (당시 러시아력 10월 25일).",
    url: "https://ko.wikipedia.org/wiki/10월_혁명",
  },
  {
    id: "un-1024-1945",
    country: "세계",
    date: "10-24",
    year: 1945,
    title: "국제연합(UN) 창설",
    era: "근현대",
    description: "세계 평화와 안전 유지를 위해 UN이 공식 출범.",
    url: "https://ko.wikipedia.org/wiki/국제_연합",
  },
  {
    id: "za-0427-1994",
    country: "남아프리카공화국",
    date: "04-27",
    year: 1994,
    title: "자유의 날",
    era: "현대",
    description: "아파르트헤이트 종식 후 첫 민주적 선거 실시.",
    url: "https://ko.wikipedia.org/wiki/아파르트헤이트",
  },
  // --- 고대/중세/근대 기타 ---
  {
    id: "eg-1023--31",
    country: "이집트",
    date: "10-23",
    year: -31,
    title: "악티움 해전",
    era: "고대",
    description: "로마 공화정 말기, 옥타비아누스가 안토니우스·클레오파트라 연합군을 격파.",
    url: "https://ko.wikipedia.org/wiki/악티움_해전",
  },
  {
    id: "it-0315--44",
    country: "이탈리아", // 로마
    date: "03-15",
    year: -44,
    title: "율리우스 카이사르 암살",
    era: "고대",
    description: "로마의 독재관 카이사르가 원로원 회의장에서 암살당함.",
    url: "https://ko.wikipedia.org/wiki/율리우스_카이사르",
  },
  {
    id: "fr-0606-1944",
    country: "프랑스",
    date: "06-06",
    year: 1944,
    title: "노르망디 상륙 작전",
    era: "근현대",
    description: "제2차 세계대전 연합군의 대규모 상륙 작전 (D-Day).",
    url: "https://ko.wikipedia.org/wiki/노르망디_상륙_작전",
  },
  {
    id: "us-0720-1969",
    country: "미국", // 우주
    date: "07-20",
    year: 1969,
    title: "아폴로 11호 달 착륙",
    era: "현대",
    description: "인류 최초로 닐 암스트롱이 달 표면에 발을 디딤.",
    url: "https://ko.wikipedia.org/wiki/아폴로_11호",
  },
  {
    id: "gb-0615-1215",
    country: "영국",
    date: "06-15",
    year: 1215,
    title: "대헌장(마그나 카르타) 서명",
    era: "중세",
    description: "왕의 권력을 제한하고 법의 지배를 명시한 문서.",
    url: "https://ko.wikipedia.org/wiki/마그나_카르타",
  },
  // --- 추가 데이터 (AI 확장) ---
  {
    id: "kr-0101-1896",
    country: "한국",
    date: "01-01",
    year: 1896,
    title: "태양력 채택",
    era: "근대",
    description: "조선, 건양(建陽) 연호를 사용하며 공식적으로 태양력 사용 시작.",
    url: "https://ko.wikipedia.org/wiki/을미개혁",
  },
  {
    id: "kr-0428-1545",
    country: "한국",
    date: "04-28",
    year: 1545,
    title: "충무공 이순신 탄신일",
    era: "중세", // 조선 중기
    description: "임진왜란에서 나라를 구한 성웅 이순신 장군이 태어난 날.",
    url: "https://ko.wikipedia.org/wiki/이순신",
  },
  {
    id: "kr-0523-2009",
    country: "한국",
    date: "05-23",
    year: 2009,
    title: "노무현 대통령 서거",
    era: "현대",
    description: "대한민국 제16대 대통령 노무현이 서거한 날.",
    url: "https://ko.wikipedia.org/wiki/노무현",
  },
  {
    id: "kr-0829-1910",
    country: "한국",
    date: "08-29",
    year: 1910,
    title: "경술국치",
    era: "근대",
    description: "한일 병합 조약이 공포되어 대한제국이 국권을 상실한 날.",
    url: "https://ko.wikipedia.org/wiki/한일_병합_조약",
  },
  {
    id: "kr-1026-1979",
    country: "한국",
    date: "10-26",
    year: 1979,
    title: "10·26 사건",
    era: "현대",
    description: "박정희 대통령이 중앙정보부장 김재규에게 시해된 사건.",
    url: "https://ko.wikipedia.org/wiki/10·26_사건",
  },
  {
    id: "kr-1212-1979",
    country: "한국",
    date: "12-12",
    year: 1979,
    title: "12·12 군사 반란",
    era: "현대",
    description: "전두환 등 신군부 세력이 일으킨 군사 반란 사건.",
    url: "https://ko.wikipedia.org/wiki/12·12_군사_반란",
  },
  {
    id: "kr-0113-1903",
    country: "한국",
    date: "01-13",
    year: 1903,
    title: "미주 한인 이민 시작",
    era: "근대",
    description: "한인 102명이 하와이 호놀룰루에 첫 도착.",
    url: "https://ko.wikipedia.org/wiki/재미_한인",
  },
  {
    id: "gb-0101-1801",
    country: "영국",
    date: "01-01",
    year: 1801,
    title: "그레이트브리튼 아일랜드 연합왕국 성립",
    era: "근대",
    description: "그레이트브리튼 왕국과 아일랜드 왕국이 통합됨.",
    url: "https://ko.wikipedia.org/wiki/그레이트브리튼_아일랜드_연합왕국",
  },
  {
    id: "jp-0108-1989",
    country: "일본",
    date: "01-08",
    year: 1989,
    title: "헤이세이 시대 시작",
    era: "현대",
    description: "쇼와 천황 사망 후 아키히토 천황 즉위, 헤이세이 연호 사용.",
    url: "https://ko.wikipedia.org/wiki/헤이세이_시대",
  },
  {
    id: "de-0118-1871",
    country: "독일",
    date: "01-18",
    year: 1871,
    title: "독일 제국 선포",
    era: "근대",
    description: "빌헬름 1세가 베르사유 궁전에서 황제로 즉위하며 독일 통일 완성.",
    url: "https://ko.wikipedia.org/wiki/독일_제국",
  },
  {
    id: "us-0120-2009",
    country: "미국",
    date: "01-20",
    year: 2009,
    title: "버락 오바마 취임",
    era: "현대",
    description: "미국 최초의 흑인 대통령 버락 오바마의 임기 시작.",
    url: "https://ko.wikipedia.org/wiki/버락_오바마",
  },
  {
    id: "in-0126-1950",
    country: "인도",
    date: "01-26",
    year: 1950,
    title: "인도 공화국 수립",
    era: "현대",
    description: "인도 헌법이 발효되며 공화국으로 전환 (리퍼블릭 데이).",
    url: "https://ko.wikipedia.org/wiki/인도의_날",
  },
  {
    id: "vn-0127-1973",
    country: "베트남",
    date: "01-27",
    year: 1973,
    title: "파리 평화 협정",
    era: "현대",
    description: "베트남 전쟁 종식을 위한 평화 협정 체결.",
    url: "https://ko.wikipedia.org/wiki/파리_평화_협정",
  },
  {
    id: "de-0130-1933",
    country: "독일",
    date: "01-30",
    year: 1933,
    title: "히틀러 총리 취임",
    era: "근현대",
    description: "아돌프 히틀러가 독일 총리로 임명되어 나치 정권 시작.",
    url: "https://ko.wikipedia.org/wiki/아돌프_히틀러",
  },
  {
    id: "ru-0201-1992",
    country: "미국",
    date: "02-01",
    year: 1992,
    title: "냉전 종식 선언 (캠프 데이비드)",
    era: "현대",
    description: "부시 미국 대통령과 옐친 러시아 대통령이 냉전 종식을 공식 선언.",
    url: "https://ko.wikipedia.org/wiki/냉전",
  },
  {
    id: "mm-0201-2021",
    country: "미얀마",
    date: "02-01",
    year: 2021,
    title: "미얀마 군사 쿠데타",
    era: "현대",
    description: "미얀마 군부가 아웅산수찌 국가고문을 구금하고 정권을 장악.",
    url: "https://ko.wikipedia.org/wiki/2021년_미얀마_쿠데타",
  },
  {
    id: "ua-0224-2022",
    country: "우크라이나",
    date: "02-24",
    year: 2022,
    title: "러시아의 우크라이나 침공",
    era: "현대",
    description: "러시아군이 우크라이나 전역을 침공하며 전쟁 발발.",
    url: "https://ko.wikipedia.org/wiki/2022년_러시아의_우크라이나_침공",
  },
  {
    id: "jp-0311-2011",
    country: "일본",
    date: "03-11",
    year: 2011,
    title: "동일본 대지진",
    era: "현대",
    description: "일본 도호쿠 지방에서 발생한 대규모 지진과 쓰나미.",
    url: "https://ko.wikipedia.org/wiki/동일본_대지진",
  },
  {
    id: "cn-0504-1919",
    country: "중국",
    date: "05-04",
    year: 1919,
    title: "5·4 운동",
    era: "근현대",
    description: "베이징 대학생들을 중심으로 일어난 반제국주의·반봉건 운동.",
    url: "https://ko.wikipedia.org/wiki/5·4_운동",
  },
  {
    id: "cn-0604-1989",
    country: "중국",
    date: "06-04",
    year: 1989,
    title: "천안문 사태",
    era: "현대",
    description: "베이징 천안문 광장에서 일어난 민주화 시위를 무력 진압한 사건.",
    url: "https://ko.wikipedia.org/wiki/1989년_천안문_사건",
  },
  {
    id: "kr-0610-1987",
    country: "한국",
    date: "06-10",
    year: 1987,
    title: "6·10 민주 항쟁",
    era: "현대",
    description: "전두환 정권의 호헌 조치에 반대하여 일어난 범국민적 민주화 운동.",
    url: "https://ko.wikipedia.org/wiki/6·10_민주_항쟁",
  },
  {
    id: "kr-0615-2000",
    country: "한국",
    date: "06-15",
    year: 2000,
    title: "6·15 남북 공동 선언",
    era: "현대",
    description: "김대중 대통령과 김정일 국방위원장이 평양에서 발표한 공동 선언.",
    url: "https://ko.wikipedia.org/wiki/6·15_남북_공동선언",
  },
  {
    id: "fr-0714-1789-dup",
    country: "프랑스",
    date: "07-14",
    year: 1789,
    title: "프랑스 혁명 기념일",
    era: "근대",
    description: "바스티유 감옥 습격을 기념하는 프랑스 국경일.",
    url: "https://ko.wikipedia.org/wiki/바스티유_감옥_습격",
  },
  {
    id: "gb-0729-1981",
    country: "영국",
    date: "07-29",
    year: 1981,
    title: "찰스 왕세자와 다이애나 결혼",
    era: "현대",
    description: "세기의 결혼식이라 불리며 전 세계에 생중계됨.",
    url: "https://ko.wikipedia.org/wiki/웨일스_공작부인_다이애나",
  },
  {
    id: "jp-0809-1945",
    country: "일본",
    date: "08-09",
    year: 1945,
    title: "나가사키 원폭 투하",
    era: "근현대",
    description: "히로시마에 이어 나가사키에 두 번째 원자폭탄이 투하됨.",
    url: "https://ko.wikipedia.org/wiki/히로시마·나가사키_원자폭탄_투하",
  },
  {
    id: "de-0901-1939",
    country: "독일",
    date: "09-01",
    year: 1939,
    title: "제2차 세계대전 발발",
    era: "근현대",
    description: "독일의 폴란드 침공으로 인류 역사상 최대 규모의 전쟁 시작.",
    url: "https://ko.wikipedia.org/wiki/제2차_세계_대전",
  },
  {
    id: "us-0915-1950",
    country: "한국",
    date: "09-15",
    year: 1950,
    title: "인천 상륙 작전",
    era: "근현대",
    description: "맥아더 장군이 지휘한 연합군의 상륙 작전으로 전세 역전.",
    url: "https://ko.wikipedia.org/wiki/인천_상륙_작전",
  },
  {
    id: "ru-1004-1957",
    country: "러시아", // 구 소련
    date: "10-04",
    year: 1957,
    title: "스푸트니크 1호 발사",
    era: "현대",
    description: "인류 최초의 인공위성 발사 성공 (우주 시대 개막).",
    url: "https://ko.wikipedia.org/wiki/스푸트니크_1호",
  },
  {
    id: "kr-1009-hangul",
    country: "한국",
    date: "10-09",
    year: 1446,
    title: "한글날",
    era: "중세",
    description: "훈민정음 반포를 기념하는 대한민국의 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/한글날",
  },
  {
    id: "us-1029-1929",
    country: "미국",
    date: "10-29",
    year: 1929,
    title: "검은 화요일 (대공황)",
    era: "근현대",
    description: "뉴욕 증시 대폭락으로 전 세계적인 경제 대공황 시작.",
    url: "https://ko.wikipedia.org/wiki/대공황",
  },
  {
    id: "gb-1105-1605",
    country: "영국",
    date: "11-05",
    year: 1605,
    title: "화약 음모 사건 (가이 포크스 데이)",
    era: "근대",
    description: "가이 포크스가 의사당을 폭파하려다 실패한 사건.",
    url: "https://ko.wikipedia.org/wiki/화약_음모_사건",
  },
  {
    id: "us-1122-1963",
    country: "미국",
    date: "11-22",
    year: 1963,
    title: "케네디 대통령 암살",
    era: "현대",
    description: "존 F. 케네디 대통령이 댈러스에서 암살당함.",
    url: "https://ko.wikipedia.org/wiki/존_F._케네디_암살_사건",
  },
  {
    id: "us-1207-1941",
    country: "미국",
    date: "12-07",
    year: 1941,
    title: "진주만 공습",
    era: "근현대",
    description: "일본군의 하와이 진주만 기습으로 미국이 제2차 세계대전에 참전.",
    url: "https://ko.wikipedia.org/wiki/진주만_공습",
  },
  // --- 추가 데이터 (2차 확장) ---
  {
    id: "kr-0228-1960",
    country: "한국",
    date: "02-28",
    year: 1960,
    title: "2·28 대구 학생 민주 의거",
    era: "현대",
    description: "이승만 정권의 독재에 항거하여 대구 지역 고등학생들이 일으킨 시위 (4·19 혁명의 도화선).",
    url: "https://ko.wikipedia.org/wiki/2·28_대구_학생_민주_의거",
  },
  {
    id: "kr-0308-1908",
    country: "세계",
    date: "03-08",
    year: 1908,
    title: "세계 여성의 날",
    era: "근대",
    description: "미국의 여성 노동자들이 참정권과 근로 조건 개선을 요구하며 시위한 날을 기념.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/세계_여성의_날",
  },
  {
    id: "kr-0315-1960",
    country: "한국",
    date: "03-15",
    year: 1960,
    title: "3·15 부정선거 및 마산 의거",
    era: "현대",
    description: "자유당 정권의 부정선거에 항의하여 마산 시민들이 일으킨 시위.",
    url: "https://ko.wikipedia.org/wiki/3·15_의거",
  },
  {
    id: "kr-0403-1948",
    country: "한국",
    date: "04-03",
    year: 1948,
    title: "제주 4·3 사건",
    era: "현대",
    description: "제주도에서 발생한 무력 충돌과 진압 과정에서 수많은 주민이 희생된 사건.",
    url: "https://ko.wikipedia.org/wiki/제주_4·3_사건",
  },
  {
    id: "kr-0416-2014",
    country: "한국",
    date: "04-16",
    year: 2014,
    title: "세월호 침몰 사고",
    era: "현대",
    description: "진도 인근 해상에서 여객선 세월호가 침몰하여 304명이 희생된 참사.",
    url: "https://ko.wikipedia.org/wiki/세월호_침몰_사고",
  },
  {
    id: "world-0501-1886",
    country: "세계",
    date: "05-01",
    year: 1886,
    title: "노동절 (메이데이)",
    era: "근대",
    description: "미국 시카고 노동자들의 파업 투쟁을 기념하는 국제적인 노동자의 날.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/노동절",
  },
  {
    id: "kr-0516-1961",
    country: "한국",
    date: "05-16",
    year: 1961,
    title: "5·16 군사 정변",
    era: "현대",
    description: "박정희 소장을 중심으로 한 군부 세력이 정권을 장악한 쿠데타.",
    url: "https://ko.wikipedia.org/wiki/5·16_군사_정변",
  },
  {
    id: "kr-0629-1995",
    country: "한국",
    date: "06-29",
    year: 1995,
    title: "삼풍백화점 붕괴 사고",
    era: "현대",
    description: "서울 서초구 삼풍백화점이 부실 공사로 인해 붕괴된 대형 참사.",
    url: "https://ko.wikipedia.org/wiki/삼풍백화점_붕괴_사고",
  },
  {
    id: "kr-0717-1948",
    country: "한국",
    date: "07-17",
    year: 1948,
    title: "제헌절",
    era: "현대",
    description: "대한민국 헌법이 제정·공포된 날을 기념하는 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/제헌절_(대한민국)",
  },
  {
    id: "kr-0727-1953",
    country: "한국",
    date: "07-27",
    year: 1953,
    title: "한국전쟁 정전 협정",
    era: "현대",
    description: "판문점에서 정전 협정이 체결되어 한국전쟁의 포성이 멈춤.",
    url: "https://ko.wikipedia.org/wiki/한국_휴전_협정",
  },
  {
    id: "jp-0815-1945-liberation",
    country: "세계",
    date: "08-15",
    year: 1945,
    title: "제2차 세계대전 종전",
    era: "근현대",
    description: "일본의 항복으로 제2차 세계대전이 공식적으로 끝남.",
    url: "https://ko.wikipedia.org/wiki/제2차_세계_대전",
  },
  {
    id: "kr-0917-1988",
    country: "한국",
    date: "09-17",
    year: 1988,
    title: "서울 올림픽 개막",
    era: "현대",
    description: "대한민국 서울에서 개최된 제24회 하계 올림픽.",
    url: "https://ko.wikipedia.org/wiki/1988년_하계_올림픽",
  },
  {
    id: "ua-0426-1986",
    country: "우크라이나", // 당시 소련
    date: "04-26",
    year: 1986,
    title: "체르노빌 원자력 발전소 사고",
    era: "현대",
    description: "역사상 최악의 원자력 발전소 폭발 사고.",
    url: "https://ko.wikipedia.org/wiki/체르노빌_원자력_발전소_사고",
  },
  {
    id: "gb-0415-1912",
    country: "영국",
    date: "04-14", // 침몰 시작은 14일 밤, 완전 침몰은 15일 새벽. 14일로 표기하기도 함.
    year: 1912,
    title: "타이타닉호 침몰",
    era: "근대",
    description: "초호화 여객선 타이타닉호가 빙산과 충돌하여 침몰.",
    url: "https://ko.wikipedia.org/wiki/RMS_타이타닉",
  },
  {
    id: "us-0412-1861",
    country: "미국",
    date: "04-12",
    year: 1861,
    title: "미국 남북 전쟁 발발",
    era: "근대",
    description: "노예제를 둘러싼 갈등으로 미국 남부와 북부 사이에 내전 발발.",
    url: "https://ko.wikipedia.org/wiki/미국_남북_전쟁",
  },
  {
    id: "at-0728-1914",
    country: "세계", // 오스트리아
    date: "07-28",
    year: 1914,
    title: "제1차 세계대전 발발",
    era: "근대",
    description: "오스트리아가 세르비아에 선전포고하며 제1차 세계대전 시작.",
    url: "https://ko.wikipedia.org/wiki/제1차_세계_대전",
  },
  {
    id: "de-1111-1918",
    country: "세계",
    date: "11-11",
    year: 1918,
    title: "제1차 세계대전 종전",
    era: "근대",
    description: "독일과 연합국 사이의 휴전 협정 체결로 1차 대전 종결.",
    url: "https://ko.wikipedia.org/wiki/제1차_세계_대전의_휴전_협정",
  },
  {
    id: "kr-1123-2010",
    country: "한국",
    date: "11-23",
    year: 2010,
    title: "연평도 포격전",
    era: "현대",
    description: "북한군이 연평도를 기습 포격하여 군인과 민간인이 희생된 사건.",
    url: "https://ko.wikipedia.org/wiki/연평도_포격전",
  },
  {
    id: "kr-1203-1997",
    country: "한국",
    date: "12-03",
    year: 1997,
    title: "IMF 구제금융 요청",
    era: "현대",
    description: "국가 부도 위기로 인해 국제통화기금(IMF)에 자금 지원을 요청하며 'IMF 사태' 시작.",
    url: "https://ko.wikipedia.org/wiki/대한민국의_IMF_구제금융_요청",
  },
  {
    id: "fr-0505-1821",
    country: "프랑스",
    date: "05-05",
    year: 1821,
    title: "나폴레옹 보나파르트 사망",
    era: "근대",
    description: "프랑스의 황제 나폴레옹 1세가 세인트헬레나 섬에서 사망.",
    url: "https://ko.wikipedia.org/wiki/나폴레옹_보나파르트",
  },
  {
    id: "us-0828-1963",
    country: "미국",
    date: "08-28",
    year: 1963,
    title: "마틴 루터 킹 '나에게는 꿈이 있습니다' 연설",
    era: "현대",
    description: "워싱턴 대행진에서 마틴 루터 킹 목사가 흑인 인권에 대한 명연설을 남김.",
    url: "https://ko.wikipedia.org/wiki/나에게는_꿈이_있습니다",
  },
  {
    id: "tr-0529-1453",
    country: "튀르키예", // 오스만 제국
    date: "05-29",
    year: 1453,
    title: "콘스탄티노폴리스 함락",
    era: "중세",
    description: "오스만 제국이 비잔틴 제국의 수도를 함락시키며 중세의 종말을 고함.",
    url: "https://ko.wikipedia.org/wiki/콘스탄티노폴리스_함락",
  },
  {
    id: "it-0824-79",
    country: "이탈리아", // 로마
    date: "08-24",
    year: 79,
    title: "폼페이 화산 폭발",
    era: "고대",
    description: "베수비오 화산 폭발로 로마 도시 폼페이가 화산재에 묻힘.",
    url: "https://ko.wikipedia.org/wiki/폼페이",
  },
  {
    id: "kr-0214-1910",
    country: "한국",
    date: "02-14",
    year: 1910,
    title: "안중근 의사 사형 선고",
    era: "근대",
    description: "이토 히로부미를 저격한 안중근 의사가 사형 선고를 받은 날.",
    url: "https://ko.wikipedia.org/wiki/안중근",
  },
  {
    id: "un-1210-1948",
    country: "세계",
    date: "12-10",
    year: 1948,
    title: "세계 인권 선언 채택",
    era: "현대",
    description: "유엔 총회에서 모든 인간의 기본적 권리를 명시한 선언을 채택.",
    url: "https://ko.wikipedia.org/wiki/세계_인권_선언",
  },
  // --- 추가 공휴일 (한국) ---
  {
    id: "kr-0301-holiday",
    country: "한국",
    date: "03-01",
    year: 2024,
    title: "삼일절",
    era: "현대",
    description: "1919년 3·1 운동을 기념하는 대한민국의 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/삼일절",
  },
  {
    id: "kr-0815-holiday",
    country: "한국",
    date: "08-15",
    year: 2024,
    title: "광복절",
    era: "현대",
    description: "1945년 일제로부터의 해방을 기념하는 대한민국의 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/광복절",
  },
  {
    id: "kr-0515-buddha-2026",
    country: "한국",
    date: "05-15",
    year: 2026,
    title: "석가탄신일 (부처님 오신 날)",
    era: "현대",
    description: "석가모니 부처의 탄생을 기념하는 날 (2026년 양력 기준 5월 15일).",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/석가탄신일",
  },
  {
    id: "kr-0925-chuseok-2026",
    country: "한국",
    date: "09-25",
    year: 2026,
    title: "추석",
    era: "현대",
    description: "한가위, 한국의 대표 명절. 2026년 양력 기준 9월 24~26일 연휴.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/추석",
  },
  {
    id: "kr-0217-seollal-2026",
    country: "한국",
    date: "02-17",
    year: 2026,
    title: "설날",
    era: "현대",
    description: "음력 1월 1일, 한국 최대의 전통 명절. 2026년 양력 기준 2월 16~18일 연휴.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/설날",
  },
  // --- 추가 공휴일 (세계) ---
  {
    id: "us-0704-holiday",
    country: "미국",
    date: "07-04",
    year: 2024,
    title: "독립기념일 (공휴일)",
    era: "현대",
    description: "미국의 독립을 기념하는 국경일 (Independence Day).",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/미국_독립기념일",
  },
  {
    id: "fr-0714-holiday",
    country: "프랑스",
    date: "07-14",
    year: 2024,
    title: "프랑스 혁명 기념일 (공휴일)",
    era: "현대",
    description: "바스티유 감옥 습격을 기념하는 프랑스 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/프랑스_혁명_기념일",
  },
  {
    id: "cn-0217-chunje-2026",
    country: "중국",
    date: "02-17",
    year: 2026,
    title: "춘절 (중국 설)",
    era: "현대",
    description: "중국 최대의 전통 명절인 춘절. 2026년 양력 기준 2월 17일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/춘절",
  },
  {
    id: "jp-0101-holiday",
    country: "일본",
    date: "01-01",
    year: 2024,
    title: "원일 (元日)",
    era: "현대",
    description: "일본의 새해 첫날 공휴일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/일본의_공휴일",
  },
  {
    id: "de-1003-holiday",
    country: "독일",
    date: "10-03",
    year: 2024,
    title: "독일 통일기념일 (공휴일)",
    era: "현대",
    description: "1990년 독일 통일을 기념하는 독일의 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/독일의_재통일",
  },
  {
    id: "in-0815-holiday",
    country: "인도",
    date: "08-15",
    year: 2024,
    title: "인도 독립기념일",
    era: "현대",
    description: "1947년 영국으로부터의 독립을 기념하는 인도의 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/인도의_독립",
  },
  {
    id: "br-0907-holiday",
    country: "브라질",
    date: "09-07",
    year: 2024,
    title: "브라질 독립기념일",
    era: "현대",
    description: "1822년 포르투갈로부터의 독립을 기념하는 브라질의 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/브라질의_독립",
  },
  {
    id: "mx-0916-holiday",
    country: "멕시코",
    date: "09-16",
    year: 2024,
    title: "멕시코 독립기념일",
    era: "현대",
    description: "1810년 스페인으로부터의 독립을 기념하는 멕시코의 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/멕시코의_독립",
  },
  {
    id: "ca-0701-holiday",
    country: "캐나다",
    date: "07-01",
    year: 2024,
    title: "캐나다 데이",
    era: "현대",
    description: "1867년 캐나다 연방 결성을 기념하는 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/캐나다_데이",
  },
  {
    id: "au-0126-holiday",
    country: "호주",
    date: "01-26",
    year: 2024,
    title: "호주 데이",
    era: "현대",
    description: "1788년 영국 함대가 시드니 항에 도착한 것을 기념하는 호주의 국경일.",
    category: "holiday",
    url: "https://ko.wikipedia.org/wiki/오스트레일리아의_날",
  },
  // --- 추가 역사 이벤트: 1월 ---
  {
    id: "us-0101-1863",
    country: "미국",
    date: "01-01",
    year: 1863,
    title: "노예해방선언 발효",
    era: "근대",
    description: "에이브러햄 링컨 대통령의 노예해방선언이 공식 발효.",
    url: "https://ko.wikipedia.org/wiki/노예_해방_선언",
  },
  {
    id: "jp-0103-1868",
    country: "일본",
    date: "01-03",
    year: 1868,
    title: "메이지 유신",
    era: "근대",
    description: "일본이 봉건체제를 타파하고 근대국가로 전환한 역사적 변혁.",
    url: "https://ko.wikipedia.org/wiki/메이지_유신",
  },
  {
    id: "cu-0101-1959",
    country: "쿠바",
    date: "01-01",
    year: 1959,
    title: "쿠바 혁명 성공",
    era: "현대",
    description: "피델 카스트로가 이끈 혁명군이 바티스타 독재 정권을 무너뜨림.",
    url: "https://ko.wikipedia.org/wiki/쿠바_혁명",
  },
  {
    id: "us-0128-1986",
    country: "미국",
    date: "01-28",
    year: 1986,
    title: "챌린저 우주왕복선 폭발",
    era: "현대",
    description: "미국 우주왕복선 챌린저호가 발사 73초 만에 공중 폭발.",
    url: "https://ko.wikipedia.org/wiki/챌린저_우주왕복선_폭발_사고",
  },
  {
    id: "in-0130-1948",
    country: "인도",
    date: "01-30",
    year: 1948,
    title: "마하트마 간디 암살",
    era: "현대",
    description: "인도 독립운동의 아버지 마하트마 간디가 힌두교 극우파에 의해 암살.",
    url: "https://ko.wikipedia.org/wiki/마하트마_간디",
  },
  {
    id: "world-0127-1945",
    country: "세계",
    date: "01-27",
    year: 1945,
    title: "아우슈비츠 수용소 해방",
    era: "근현대",
    description: "소련군이 아우슈비츠 강제 수용소를 해방. 이 날은 국제 홀로코스트 추모일.",
    url: "https://ko.wikipedia.org/wiki/아우슈비츠_강제_수용소",
  },
  // --- 추가 역사 이벤트: 2월 ---
  {
    id: "world-0204-1945",
    country: "세계",
    date: "02-04",
    year: 1945,
    title: "얄타 회담",
    era: "근현대",
    description: "루스벨트, 처칠, 스탈린이 전후 세계 질서를 논의한 정상회담.",
    url: "https://ko.wikipedia.org/wiki/얄타_회담",
  },
  {
    id: "world-0221-1848",
    country: "세계",
    date: "02-21",
    year: 1848,
    title: "공산당 선언 발표",
    era: "근대",
    description: "카를 마르크스와 프리드리히 엥겔스가 공산당 선언을 발표.",
    url: "https://ko.wikipedia.org/wiki/공산당_선언",
  },
  {
    id: "ru-0223-1917",
    country: "러시아",
    date: "02-23",
    year: 1917,
    title: "러시아 2월 혁명",
    era: "근대",
    description: "러시아 제국의 차르 체제가 무너진 혁명 (율리우스력 2월 23일).",
    url: "https://ko.wikipedia.org/wiki/2월_혁명",
  },
  {
    id: "us-0220-1962",
    country: "미국",
    date: "02-20",
    year: 1962,
    title: "존 글렌 우주 비행",
    era: "현대",
    description: "존 글렌이 미국인 최초로 지구 궤도를 비행.",
    url: "https://ko.wikipedia.org/wiki/존_글렌",
  },
  {
    id: "ru-0219-1861",
    country: "러시아",
    date: "02-19",
    year: 1861,
    title: "러시아 농노 해방",
    era: "근대",
    description: "알렉산드르 2세가 농노 해방령을 선포하여 러시아의 농노제 폐지.",
    url: "https://ko.wikipedia.org/wiki/1861년_러시아_농노_해방",
  },
  {
    id: "eg-0216-1922",
    country: "이집트",
    date: "02-16",
    year: 1922,
    title: "투탕카멘 무덤 발견",
    era: "근현대",
    description: "하워드 카터가 이집트 왕가의 계곡에서 투탕카멘의 무덤을 발견.",
    url: "https://ko.wikipedia.org/wiki/투탕카멘",
  },
  // --- 추가 역사 이벤트: 3월 ---
  {
    id: "kr-0326-1910",
    country: "한국",
    date: "03-26",
    year: 1910,
    title: "안중근 의사 순국",
    era: "근대",
    description: "이토 히로부미를 저격한 안중근 의사가 뤼순 감옥에서 순국.",
    url: "https://ko.wikipedia.org/wiki/안중근",
  },
  {
    id: "ru-0305-1953",
    country: "러시아",
    date: "03-05",
    year: 1953,
    title: "스탈린 사망",
    era: "현대",
    description: "소비에트 연방의 최고 지도자 이오시프 스탈린이 사망.",
    url: "https://ko.wikipedia.org/wiki/이오시프_스탈린",
  },
  {
    id: "world-0328-1854",
    country: "세계",
    date: "03-28",
    year: 1854,
    title: "크림 전쟁 시작",
    era: "근대",
    description: "영국과 프랑스가 러시아에 선전포고하며 크림 전쟁 본격화.",
    url: "https://ko.wikipedia.org/wiki/크림_전쟁",
  },
  {
    id: "sy-0315-2011",
    country: "시리아",
    date: "03-15",
    year: 2011,
    title: "시리아 내전 시작",
    era: "현대",
    description: "반정부 시위가 내전으로 확대된 시리아 분쟁의 시작.",
    url: "https://ko.wikipedia.org/wiki/시리아_내전",
  },
  {
    id: "us-0401-1976",
    country: "미국",
    date: "04-01",
    year: 1976,
    title: "애플 설립",
    era: "현대",
    description: "스티브 잡스, 스티브 워즈니악, 로널드 웨인이 애플 컴퓨터를 설립.",
    url: "https://ko.wikipedia.org/wiki/애플_(기업)",
  },
  {
    id: "kr-0301-1947",
    country: "한국",
    date: "03-01",
    year: 1947,
    title: "제주 3·1절 발포 사건",
    era: "현대",
    description: "제주도에서 3·1절 기념 시위 중 경찰이 발포하여 사상자 발생 (4·3 사건의 도화선).",
    url: "https://ko.wikipedia.org/wiki/제주_4·3_사건",
  },
  {
    id: "it-0317-1861",
    country: "이탈리아",
    date: "03-17",
    year: 1861,
    title: "이탈리아 통일 왕국 선포",
    era: "근대",
    description: "비토리오 에마누엘레 2세가 이탈리아 통일 왕국의 수립을 선포.",
    url: "https://ko.wikipedia.org/wiki/이탈리아_통일",
  },
  // --- 추가 역사 이벤트: 4월 ---
  {
    id: "de-0430-1945",
    country: "독일",
    date: "04-30",
    year: 1945,
    title: "히틀러 자살",
    era: "근현대",
    description: "아돌프 히틀러가 베를린 총통 지하벙커에서 자살.",
    url: "https://ko.wikipedia.org/wiki/아돌프_히틀러의_죽음",
  },
  {
    id: "ru-0412-1961",
    country: "러시아",
    date: "04-12",
    year: 1961,
    title: "유리 가가린 우주비행",
    era: "현대",
    description: "소련의 유리 가가린이 인류 최초로 우주 비행에 성공.",
    url: "https://ko.wikipedia.org/wiki/유리_가가린",
  },
  {
    id: "vn-0430-1975",
    country: "베트남",
    date: "04-30",
    year: 1975,
    title: "사이공 함락 (베트남 전쟁 종전)",
    era: "현대",
    description: "북베트남군이 사이공을 점령하며 베트남 전쟁이 종결.",
    url: "https://ko.wikipedia.org/wiki/사이공_함락",
  },
  {
    id: "rw-0406-1994",
    country: "르완다",
    date: "04-06",
    year: 1994,
    title: "르완다 학살 시작",
    era: "현대",
    description: "후투족 극단주의자들에 의한 투치족 대량 학살이 시작됨.",
    url: "https://ko.wikipedia.org/wiki/르완다_집단_학살",
  },
  {
    id: "us-0414-1865",
    country: "미국",
    date: "04-14",
    year: 1865,
    title: "에이브러햄 링컨 암살",
    era: "근대",
    description: "미국 제16대 대통령 링컨이 극장에서 존 윌크스 부스에 의해 암살.",
    url: "https://ko.wikipedia.org/wiki/에이브러햄_링컨의_암살",
  },
  {
    id: "ir-0401-1979",
    country: "이란",
    date: "04-01",
    year: 1979,
    title: "이란 이슬람 공화국 수립",
    era: "현대",
    description: "이란 혁명 후 호메이니가 이슬람 공화국 수립을 선포.",
    url: "https://ko.wikipedia.org/wiki/이란_혁명",
  },
  {
    id: "world-0422-1970",
    country: "세계",
    date: "04-22",
    year: 1970,
    title: "최초의 지구의 날",
    era: "현대",
    description: "환경 보호의 중요성을 알리는 지구의 날이 처음 시행됨.",
    url: "https://ko.wikipedia.org/wiki/지구의_날",
  },
  // --- 추가 역사 이벤트: 5월 ---
  {
    id: "world-0508-1945",
    country: "세계",
    date: "05-08",
    year: 1945,
    title: "유럽 전승기념일 (V-E Day)",
    era: "근현대",
    description: "나치 독일의 무조건 항복으로 유럽 전선의 제2차 세계대전 종결.",
    url: "https://ko.wikipedia.org/wiki/유럽_전승_기념일",
  },
  {
    id: "fr-0505-1789",
    country: "프랑스",
    date: "05-05",
    year: 1789,
    title: "프랑스 삼부회 소집",
    era: "근대",
    description: "루이 16세가 삼부회를 소집하며 프랑스 혁명의 서막이 열림.",
    url: "https://ko.wikipedia.org/wiki/삼부회",
  },
  {
    id: "gb-0506-1840",
    country: "영국",
    date: "05-06",
    year: 1840,
    title: "세계 최초 우편 제도 시행",
    era: "근대",
    description: "영국에서 페니 블랙 우표를 발행하며 근대 우편 제도 시작.",
    url: "https://ko.wikipedia.org/wiki/페니_블랙",
  },
  {
    id: "world-0514-1955",
    country: "세계",
    date: "05-14",
    year: 1955,
    title: "바르샤바 조약기구 결성",
    era: "현대",
    description: "소련과 동유럽 국가들이 NATO에 대항하여 군사 동맹을 결성.",
    url: "https://ko.wikipedia.org/wiki/바르샤바_조약_기구",
  },
  {
    id: "il-0514-1948",
    country: "이스라엘",
    date: "05-14",
    year: 1948,
    title: "이스라엘 건국 선언",
    era: "현대",
    description: "다비드 벤구리온이 이스라엘의 독립을 선포.",
    url: "https://ko.wikipedia.org/wiki/이스라엘의_독립_선언",
  },
  {
    id: "gb-0508-1886",
    country: "영국",
    date: "05-08",
    year: 1886,
    title: "코카콜라 발명",
    era: "근대",
    description: "미국 조지아주 애틀랜타에서 약사 존 펨버턴이 코카콜라를 처음 제조.",
    url: "https://ko.wikipedia.org/wiki/코카콜라",
  },
  // --- 추가 역사 이벤트: 6월 ---
  {
    id: "kr-0628-1950",
    country: "한국",
    date: "06-28",
    year: 1950,
    title: "서울 함락 (한국전쟁)",
    era: "근현대",
    description: "한국전쟁 발발 3일 만에 북한군이 서울을 점령.",
    url: "https://ko.wikipedia.org/wiki/서울_전투_(1950년_6월)",
  },
  {
    id: "us-0628-1969",
    country: "미국",
    date: "06-28",
    year: 1969,
    title: "스톤월 항쟁",
    era: "현대",
    description: "뉴욕 스톤월 인에서 성소수자 인권 운동이 시작된 사건.",
    url: "https://ko.wikipedia.org/wiki/스톤월_항쟁",
  },
  {
    id: "in-0625-1975",
    country: "인도",
    date: "06-25",
    year: 1975,
    title: "인도 비상사태 선포",
    era: "현대",
    description: "인디라 간디 총리가 국가 비상사태를 선포하여 민주주의가 중단됨.",
    url: "https://ko.wikipedia.org/wiki/인도_비상사태_(1975년)",
  },
  {
    id: "at-0628-1914",
    country: "세계",
    date: "06-28",
    year: 1914,
    title: "사라예보 사건",
    era: "근대",
    description: "오스트리아-헝가리 제국의 프란츠 페르디난트 대공이 사라예보에서 암살당해 1차 대전의 도화선이 됨.",
    url: "https://ko.wikipedia.org/wiki/사라예보_사건",
  },
  {
    id: "world-0620-1945",
    country: "세계",
    date: "06-26",
    year: 1945,
    title: "유엔 헌장 서명",
    era: "근현대",
    description: "50개국 대표가 샌프란시스코에서 유엔 헌장에 서명.",
    url: "https://ko.wikipedia.org/wiki/국제_연합_헌장",
  },
  // --- 추가 역사 이벤트: 7월 ---
  {
    id: "cn-0707-1937",
    country: "중국",
    date: "07-07",
    year: 1937,
    title: "중일전쟁 발발 (루거우차오 사건)",
    era: "근현대",
    description: "루거우차오(노구교) 사건으로 중일전쟁이 전면적으로 발발.",
    url: "https://ko.wikipedia.org/wiki/루거우차오_사건",
  },
  {
    id: "us-0716-1945",
    country: "미국",
    date: "07-16",
    year: 1945,
    title: "트리니티 핵실험",
    era: "근현대",
    description: "인류 최초의 핵폭탄 실험이 미국 뉴멕시코주에서 성공.",
    url: "https://ko.wikipedia.org/wiki/트리니티_(핵실험)",
  },
  {
    id: "iq-0716-1979",
    country: "이라크",
    date: "07-16",
    year: 1979,
    title: "사담 후세인 이라크 대통령 취임",
    era: "현대",
    description: "사담 후세인이 이라크의 대통령으로 취임.",
    url: "https://ko.wikipedia.org/wiki/사담_후세인",
  },
  {
    id: "world-0701-2002",
    country: "세계",
    date: "07-01",
    year: 2002,
    title: "국제형사재판소(ICC) 설립",
    era: "현대",
    description: "로마 규정이 발효되며 국제형사재판소가 공식 출범.",
    url: "https://ko.wikipedia.org/wiki/국제_형사_재판소",
  },
  {
    id: "eg-0721-1798",
    country: "이집트",
    date: "07-21",
    year: 1798,
    title: "피라미드 전투",
    era: "근대",
    description: "나폴레옹이 이끈 프랑스군이 이집트 맘루크 군대를 격파.",
    url: "https://ko.wikipedia.org/wiki/피라미드_전투",
  },
  {
    id: "es-0717-1936",
    country: "스페인",
    date: "07-17",
    year: 1936,
    title: "스페인 내전 발발",
    era: "근현대",
    description: "프랑코 장군의 군사 반란으로 스페인 내전이 시작.",
    url: "https://ko.wikipedia.org/wiki/스페인_내전",
  },
  // --- 추가 역사 이벤트: 8월 ---
  {
    id: "jp-0814-1945",
    country: "일본",
    date: "08-14",
    year: 1945,
    title: "일본 항복 결정 (포츠담 선언 수락)",
    era: "근현대",
    description: "일본 천황이 포츠담 선언을 수락하고 항복을 결정.",
    url: "https://ko.wikipedia.org/wiki/일본의_항복",
  },
  {
    id: "in-0815-1947",
    country: "인도",
    date: "08-15",
    year: 1947,
    title: "인도 독립",
    era: "현대",
    description: "영국의 식민 지배에서 벗어나 인도가 독립을 선언.",
    url: "https://ko.wikipedia.org/wiki/인도의_독립",
  },
  {
    id: "de-0813-1961",
    country: "독일",
    date: "08-13",
    year: 1961,
    title: "베를린 장벽 건설 시작",
    era: "현대",
    description: "동독 정부가 서베를린과의 경계에 장벽 건설을 시작.",
    url: "https://ko.wikipedia.org/wiki/베를린_장벽",
  },
  {
    id: "iq-0802-1990",
    country: "이라크",
    date: "08-02",
    year: 1990,
    title: "이라크의 쿠웨이트 침공",
    era: "현대",
    description: "사담 후세인이 이끄는 이라크군이 쿠웨이트를 침공하며 걸프전의 시작.",
    url: "https://ko.wikipedia.org/wiki/쿠웨이트_침공",
  },
  {
    id: "jp-0802-1945",
    country: "일본",
    date: "08-02",
    year: 1945,
    title: "포츠담 회담 종료",
    era: "근현대",
    description: "연합국 수뇌들이 전후 처리를 논의한 포츠담 회담이 종료.",
    url: "https://ko.wikipedia.org/wiki/포츠담_회담",
  },
  {
    id: "us-0821-1959",
    country: "미국",
    date: "08-21",
    year: 1959,
    title: "하와이 미국 50번째 주 편입",
    era: "현대",
    description: "하와이가 미국의 50번째 주로 공식 편입.",
    url: "https://ko.wikipedia.org/wiki/하와이주",
  },
  // --- 추가 역사 이벤트: 9월 ---
  {
    id: "jp-0902-1945",
    country: "일본",
    date: "09-02",
    year: 1945,
    title: "일본 항복 조인식",
    era: "근현대",
    description: "도쿄만 미주리호 선상에서 일본이 공식 항복 문서에 서명.",
    url: "https://ko.wikipedia.org/wiki/일본의_항복",
  },
  {
    id: "jp-0901-1923",
    country: "일본",
    date: "09-01",
    year: 1923,
    title: "관동 대지진",
    era: "근현대",
    description: "일본 관동 지방에 진도 7.9의 대지진 발생. 10만 명 이상 사망.",
    url: "https://ko.wikipedia.org/wiki/1923년_관동_대지진",
  },
  {
    id: "us-0915-2008",
    country: "미국",
    date: "09-15",
    year: 2008,
    title: "리먼 브라더스 파산 (글로벌 금융위기)",
    era: "현대",
    description: "미국 투자은행 리먼 브라더스의 파산으로 글로벌 금융위기 본격화.",
    url: "https://ko.wikipedia.org/wiki/리먼_브라더스",
  },
  {
    id: "br-0907-1822",
    country: "브라질",
    date: "09-07",
    year: 1822,
    title: "브라질 독립",
    era: "근대",
    description: "포르투갈로부터 브라질이 독립을 선언.",
    url: "https://ko.wikipedia.org/wiki/브라질의_독립",
  },
  {
    id: "mx-0916-1810",
    country: "멕시코",
    date: "09-16",
    year: 1810,
    title: "멕시코 독립운동 시작",
    era: "근대",
    description: "미겔 이달고 신부의 '돌로레스의 외침'으로 멕시코 독립운동이 시작.",
    url: "https://ko.wikipedia.org/wiki/멕시코_독립_전쟁",
  },
  {
    id: "kr-0928-1972",
    country: "한국",
    date: "09-28",
    year: 1950,
    title: "서울 수복",
    era: "근현대",
    description: "인천 상륙 작전 후 국군과 유엔군이 서울을 되찾음.",
    url: "https://ko.wikipedia.org/wiki/서울_전투_(1950년_9월)",
  },
  // --- 추가 역사 이벤트: 10월 ---
  {
    id: "us-1012-1492",
    country: "미국",
    date: "10-12",
    year: 1492,
    title: "콜럼버스 아메리카 도착",
    era: "근대",
    description: "크리스토퍼 콜럼버스가 아메리카 대륙에 도달.",
    url: "https://ko.wikipedia.org/wiki/크리스토퍼_콜럼버스",
  },
  {
    id: "us-1016-1962",
    country: "미국",
    date: "10-16",
    year: 1962,
    title: "쿠바 미사일 위기",
    era: "현대",
    description: "소련이 쿠바에 핵미사일을 배치한 것이 발각되며 미·소 핵전쟁 위기가 고조.",
    url: "https://ko.wikipedia.org/wiki/쿠바_미사일_위기",
  },
  {
    id: "jp-1010-1964",
    country: "일본",
    date: "10-10",
    year: 1964,
    title: "도쿄 올림픽 개막",
    era: "현대",
    description: "아시아 최초의 올림픽인 1964년 도쿄 하계 올림픽 개막.",
    url: "https://ko.wikipedia.org/wiki/1964년_하계_올림픽",
  },
  {
    id: "fr-1005-1789",
    country: "프랑스",
    date: "10-05",
    year: 1789,
    title: "베르사유 행진",
    era: "근대",
    description: "파리 여성들이 식량 부족에 항의하며 베르사유 궁전으로 행진.",
    url: "https://ko.wikipedia.org/wiki/베르사유_행진",
  },
  {
    id: "cn-1010-1911",
    country: "중국",
    date: "10-10",
    year: 1911,
    title: "신해혁명",
    era: "근대",
    description: "중국에서 청나라를 무너뜨리고 공화정을 수립한 혁명.",
    url: "https://ko.wikipedia.org/wiki/신해혁명",
  },
  {
    id: "world-1031-1517",
    country: "독일",
    date: "10-31",
    year: 1517,
    title: "마르틴 루터 95개 논제",
    era: "근대",
    description: "마르틴 루터가 95개 논제를 발표하며 종교개혁의 시작을 알림.",
    url: "https://ko.wikipedia.org/wiki/95개조_논제",
  },
  {
    id: "us-1024-1929",
    country: "미국",
    date: "10-24",
    year: 1929,
    title: "검은 목요일",
    era: "근현대",
    description: "뉴욕 증시가 대폭락하며 대공황의 서막이 열린 날.",
    url: "https://ko.wikipedia.org/wiki/1929년_월스트리트_대폭락",
  },
  // --- 추가 역사 이벤트: 11월 ---
  {
    id: "de-1109-1918",
    country: "독일",
    date: "11-09",
    year: 1918,
    title: "독일 혁명 (바이마르 공화국 수립)",
    era: "근대",
    description: "독일 제국이 무너지고 공화국이 선포됨.",
    url: "https://ko.wikipedia.org/wiki/독일_혁명",
  },
  {
    id: "fr-1109-1799",
    country: "프랑스",
    date: "11-09",
    year: 1799,
    title: "나폴레옹 쿠데타 (브뤼메르 18일)",
    era: "근대",
    description: "나폴레옹 보나파르트가 쿠데타로 프랑스 정권을 장악.",
    url: "https://ko.wikipedia.org/wiki/브뤼메르_18일의_쿠데타",
  },
  {
    id: "us-1111-1620",
    country: "미국",
    date: "11-11",
    year: 1620,
    title: "메이플라워호 도착",
    era: "근대",
    description: "영국 청교도들이 메이플라워호를 타고 아메리카 대륙에 도착.",
    url: "https://ko.wikipedia.org/wiki/메이플라워호",
  },
  {
    id: "fr-1113-2015",
    country: "프랑스",
    date: "11-13",
    year: 2015,
    title: "파리 테러",
    era: "현대",
    description: "IS에 의한 파리 동시다발 테러로 130명 이상 사망.",
    url: "https://ko.wikipedia.org/wiki/2015년_11월_파리_테러",
  },
  {
    id: "world-1110-1938",
    country: "독일",
    date: "11-10",
    year: 1938,
    title: "수정의 밤 (크리스탈나흐트)",
    era: "근현대",
    description: "나치 독일에서 유대인을 대상으로 한 대규모 폭력 사건.",
    url: "https://ko.wikipedia.org/wiki/수정의_밤",
  },
  {
    id: "us-1119-1863",
    country: "미국",
    date: "11-19",
    year: 1863,
    title: "게티즈버그 연설",
    era: "근대",
    description: "에이브러햄 링컨 대통령이 게티즈버그에서 유명한 연설을 행함.",
    url: "https://ko.wikipedia.org/wiki/게티즈버그_연설",
  },
  // --- 추가 역사 이벤트: 12월 ---
  {
    id: "ru-1225-1991",
    country: "러시아",
    date: "12-25",
    year: 1991,
    title: "소련 해체",
    era: "현대",
    description: "미하일 고르바초프 대통령이 사임하며 소비에트 연방이 공식 해체.",
    url: "https://ko.wikipedia.org/wiki/소련의_해체",
  },
  {
    id: "us-1217-1903",
    country: "미국",
    date: "12-17",
    year: 1903,
    title: "라이트 형제 첫 비행",
    era: "근대",
    description: "라이트 형제가 키티호크에서 인류 최초의 동력 비행에 성공.",
    url: "https://ko.wikipedia.org/wiki/라이트_형제",
  },
  {
    id: "jp-1208-1941",
    country: "일본",
    date: "12-08",
    year: 1941,
    title: "태평양 전쟁 발발",
    era: "근현대",
    description: "일본이 진주만을 공격하며 태평양 전쟁을 선언 (일본 시간 12월 8일).",
    url: "https://ko.wikipedia.org/wiki/태평양_전쟁",
  },
  {
    id: "kr-1212-1948",
    country: "한국",
    date: "12-12",
    year: 1948,
    title: "대한민국 UN 승인",
    era: "현대",
    description: "유엔 총회에서 대한민국 정부를 한반도 유일 합법 정부로 승인.",
    url: "https://ko.wikipedia.org/wiki/유엔_총회_결의_제195호",
  },
  {
    id: "fr-1202-1804",
    country: "프랑스",
    date: "12-02",
    year: 1804,
    title: "나폴레옹 황제 대관식",
    era: "근대",
    description: "나폴레옹 보나파르트가 노트르담 대성당에서 황제로 즉위.",
    url: "https://ko.wikipedia.org/wiki/나폴레옹_보나파르트",
  },
  {
    id: "us-1216-1773",
    country: "미국",
    date: "12-16",
    year: 1773,
    title: "보스턴 차 사건",
    era: "근대",
    description: "영국의 차세(茶稅)에 항의하여 식민지 주민들이 보스턴 항에서 차를 바다에 버린 사건.",
    url: "https://ko.wikipedia.org/wiki/보스턴_차_사건",
  },
  {
    id: "world-1201-1955",
    country: "미국",
    date: "12-01",
    year: 1955,
    title: "로자 파크스 버스 거부 사건",
    era: "현대",
    description: "로자 파크스가 버스에서 백인에게 자리 양보를 거부하여 흑인 민권 운동에 불을 지핌.",
    url: "https://ko.wikipedia.org/wiki/로자_파크스",
  },
  {
    id: "world-1220-1999",
    country: "세계",
    date: "12-20",
    year: 1999,
    title: "마카오 반환",
    era: "현대",
    description: "포르투갈이 마카오의 주권을 중국에 반환.",
    url: "https://ko.wikipedia.org/wiki/마카오_반환",
  },
  {
    id: "world-1226-2004",
    country: "세계",
    date: "12-26",
    year: 2004,
    title: "인도양 대지진과 쓰나미",
    era: "현대",
    description: "인도양에서 규모 9.1의 대지진과 쓰나미가 발생하여 23만 명 이상 사망.",
    url: "https://ko.wikipedia.org/wiki/2004년_인도양_지진_해일",
  },
  // --- 추가 역사 이벤트: 보충 (월별 균형) ---
  {
    id: "gb-0115-1759",
    country: "영국",
    date: "01-15",
    year: 1759,
    title: "대영박물관 개관",
    era: "근대",
    description: "런던에 세계 최초의 공공 국립 박물관인 대영박물관이 개관.",
    url: "https://ko.wikipedia.org/wiki/대영_박물관",
  },
  {
    id: "us-0204-2004",
    country: "미국",
    date: "02-04",
    year: 2004,
    title: "페이스북 설립",
    era: "현대",
    description: "마크 저커버그가 하버드대 기숙사에서 페이스북을 설립.",
    url: "https://ko.wikipedia.org/wiki/페이스북",
  },
  {
    id: "world-0312-1930",
    country: "인도",
    date: "03-12",
    year: 1930,
    title: "간디의 소금 행진",
    era: "근현대",
    description: "마하트마 간디가 영국의 소금세에 항의하여 388km 행진을 시작.",
    url: "https://ko.wikipedia.org/wiki/소금_행진",
  },
  {
    id: "world-0425-1953",
    country: "영국",
    date: "04-25",
    year: 1953,
    title: "DNA 이중나선 구조 발표",
    era: "현대",
    description: "왓슨과 크릭이 네이처지에 DNA 이중나선 구조 논문을 발표.",
    url: "https://ko.wikipedia.org/wiki/DNA",
  },
  {
    id: "world-0512-2008",
    country: "중국",
    date: "05-12",
    year: 2008,
    title: "쓰촨성 대지진",
    era: "현대",
    description: "중국 쓰촨성에서 규모 8.0의 대지진이 발생하여 약 7만 명 사망.",
    url: "https://ko.wikipedia.org/wiki/2008년_쓰촨성_대지진",
  },
  {
    id: "world-0617-1972",
    country: "미국",
    date: "06-17",
    year: 1972,
    title: "워터게이트 사건",
    era: "현대",
    description: "워터게이트 빌딩 민주당 본부에 도청 장치를 설치하려다 발각된 정치 스캔들.",
    url: "https://ko.wikipedia.org/wiki/워터게이트_사건",
  },
  {
    id: "world-0711-1995",
    country: "세계",
    date: "07-11",
    year: 1995,
    title: "스레브레니차 학살",
    era: "현대",
    description: "보스니아 전쟁 중 세르비아군이 스레브레니차에서 8천여 명을 학살.",
    url: "https://ko.wikipedia.org/wiki/스레브레니차_학살",
  },
  {
    id: "world-0812-1981",
    country: "미국",
    date: "08-12",
    year: 1981,
    title: "IBM PC 출시",
    era: "현대",
    description: "IBM이 최초의 개인용 컴퓨터(IBM PC)를 출시하며 PC 시대를 개막.",
    url: "https://ko.wikipedia.org/wiki/IBM_PC",
  },
  {
    id: "world-0903-1783",
    country: "미국",
    date: "09-03",
    year: 1783,
    title: "파리 조약 (미국 독립 승인)",
    era: "근대",
    description: "영국이 파리 조약에 서명하며 미국의 독립을 공식 승인.",
    url: "https://ko.wikipedia.org/wiki/파리_조약_(1783년)",
  },
  {
    id: "world-1014-1066",
    country: "영국",
    date: "10-14",
    year: 1066,
    title: "헤이스팅스 전투",
    era: "중세",
    description: "노르만 공 윌리엄이 잉글랜드를 정복한 결정적 전투.",
    url: "https://ko.wikipedia.org/wiki/헤이스팅스_전투",
  },
  {
    id: "ru-1107-1917-dup",
    country: "러시아",
    date: "11-07",
    year: 1917,
    title: "볼셰비키 겨울궁전 점령",
    era: "근대",
    description: "볼셰비키가 상트페테르부르크의 겨울궁전을 점령하며 소비에트 정권 수립.",
    url: "https://ko.wikipedia.org/wiki/10월_혁명",
  },
  {
    id: "kr-1217-1997",
    country: "한국",
    date: "12-18",
    year: 1997,
    title: "김대중 대통령 당선",
    era: "현대",
    description: "대한민국 최초의 여야 정권 교체로 김대중 후보가 대통령에 당선.",
    url: "https://ko.wikipedia.org/wiki/김대중",
  },
  {
    id: "world-0609-68",
    country: "이탈리아",
    date: "06-09",
    year: 68,
    title: "네로 황제 자살",
    era: "고대",
    description: "로마 제국의 폭군 네로가 반란에 직면하여 자살.",
    url: "https://ko.wikipedia.org/wiki/네로",
  },
  {
    id: "gr-0490-marathon",
    country: "그리스",
    date: "09-12",
    year: -490,
    title: "마라톤 전투",
    era: "고대",
    description: "그리스 아테네가 페르시아 제국의 침공을 마라톤 평원에서 격퇴.",
    url: "https://ko.wikipedia.org/wiki/마라톤_전투",
  },
  {
    id: "it-0904-476",
    country: "이탈리아",
    date: "09-04",
    year: 476,
    title: "서로마 제국 멸망",
    era: "고대",
    description: "게르만족 용병대장 오도아케르가 마지막 서로마 황제를 폐위시킴.",
    url: "https://ko.wikipedia.org/wiki/서로마_제국",
  },
  {
    id: "mn-1206-1206",
    country: "몽골",
    date: "01-01",
    year: 1206,
    title: "칭기즈 칸 몽골 통일",
    era: "중세",
    description: "테무진이 칭기즈 칸으로 추대되며 몽골 제국을 건설.",
    url: "https://ko.wikipedia.org/wiki/칭기즈_칸",
  },
  {
    id: "gb-0319-1649",
    country: "영국",
    date: "01-30",
    year: 1649,
    title: "찰스 1세 처형",
    era: "근대",
    description: "영국 내전 후 찰스 1세가 반역죄로 처형됨.",
    url: "https://ko.wikipedia.org/wiki/찰스_1세_(잉글랜드)",
  },
  {
    id: "us-0901-1983",
    country: "세계",
    date: "09-01",
    year: 1983,
    title: "대한항공 007편 격추 사건",
    era: "현대",
    description: "소련 전투기가 대한항공 여객기를 격추하여 269명 전원 사망.",
    url: "https://ko.wikipedia.org/wiki/대한항공_007편_격추_사건",
  },
  {
    id: "world-0111-2020",
    country: "세계",
    date: "01-11",
    year: 2020,
    title: "코로나19 첫 사망자 발생",
    era: "현대",
    description: "중국 우한에서 신종 코로나바이러스 감염증의 첫 사망자가 보고됨.",
    url: "https://ko.wikipedia.org/wiki/코로나바이러스감염증-19",
  },
  {
    id: "world-0311-2020",
    country: "세계",
    date: "03-11",
    year: 2020,
    title: "WHO 코로나19 팬데믹 선언",
    era: "현대",
    description: "세계보건기구(WHO)가 코로나19를 세계적 대유행(팬데믹)으로 선언.",
    url: "https://ko.wikipedia.org/wiki/코로나바이러스감염증-19_범유행",
  },
  {
    id: "us-0107-2021",
    country: "미국",
    date: "01-06",
    year: 2021,
    title: "미국 의사당 난입 사건",
    era: "현대",
    description: "트럼프 지지자들이 미국 연방 의사당에 난입한 사건.",
    url: "https://ko.wikipedia.org/wiki/2021년_미국_의회_의사당_습격",
  },
  {
    id: "gb-0701-1997",
    country: "영국",
    date: "07-01",
    year: 1997,
    title: "홍콩 반환",
    era: "현대",
    description: "영국이 홍콩의 주권을 중국에 반환.",
    url: "https://ko.wikipedia.org/wiki/홍콩_반환",
  },
  {
    id: "world-0420-2010",
    country: "미국",
    date: "04-20",
    year: 2010,
    title: "딥워터 호라이즌 기름 유출 사고",
    era: "현대",
    description: "멕시코만에서 BP 석유 시추 시설 폭발로 역사상 최악의 해양 기름 유출 사고 발생.",
    url: "https://ko.wikipedia.org/wiki/딥워터_호라이즌_기름_유출_사고",
  },
  {
    id: "jp-0501-2019",
    country: "일본",
    date: "05-01",
    year: 2019,
    title: "레이와 시대 시작",
    era: "현대",
    description: "나루히토 천황이 즉위하며 레이와(令和) 연호가 시작됨.",
    url: "https://ko.wikipedia.org/wiki/레이와_시대",
  },
  {
    id: "world-0806-1991",
    country: "세계",
    date: "08-06",
    year: 1991,
    title: "월드 와이드 웹 공개",
    era: "현대",
    description: "팀 버너스리가 월드 와이드 웹(WWW)을 일반에 공개.",
    url: "https://ko.wikipedia.org/wiki/월드_와이드_웹",
  },
  {
    id: "kr-0402-2018",
    country: "한국",
    date: "04-27",
    year: 2018,
    title: "판문점 남북정상회담",
    era: "현대",
    description: "문재인 대통령과 김정은 위원장이 판문점에서 남북정상회담을 개최.",
    url: "https://ko.wikipedia.org/wiki/2018년_4월_남북정상회담",
  },
  {
    id: "eg-1104-1922",
    country: "이집트",
    date: "11-04",
    year: 1922,
    title: "투탕카멘 무덤 입구 발견",
    era: "근현대",
    description: "하워드 카터가 왕가의 계곡에서 투탕카멘 무덤의 입구를 발견.",
    url: "https://ko.wikipedia.org/wiki/KV62",
  },
  {
    id: "world-0614-1777",
    country: "미국",
    date: "06-14",
    year: 1777,
    title: "성조기 제정",
    era: "근대",
    description: "미국 대륙의회가 성조기를 미국의 공식 국기로 채택.",
    url: "https://ko.wikipedia.org/wiki/미국의_국기",
  },
];
